### ISSUE TITLE
Gamma Settings Not Automatically Initializing

### ISSUE THREAD

**Issue by IceMaverick** [HaloSPV3/HCE#1]
The gamma settings aren't actually setting themselves to their saved value unless you visit the Video Settings menu after launching the game. Visiting the menu causes the gamma to correctly adjust to its set value simply by opening it. If you don't visit this menu prior to entering a mission, the Gamma settings never adjust.

Alternatively, the Gamma value in the Video Settings menu is not synced with the Gamma value in the Loader Settings and the two values have different fields of scope as to when their own saved values affect the game.

**Comment by yumiris** [comment]
That's rather strange. Can you run SPV3 in window mode with a brightness
of 200 in the loader? Your entire screen should become jarringly white
the moment SPV3 starts up.

Regarding the gamma settings being out of sync, this is because the
loader declares the gamma inside the initc.txt file, rather than the
profile gamma.

**Comment by IceMaverick** [comment]
So running in windowed mode does some interesting things:
1. The screen is actually not blinding at 200 in windowed mode it's just simply really bright and washed out because of the amount of white. In fullscreen mode, 200 is so much that the screen is literally just white with some splotches of yellow and magenta over the absolute darkest parts of the image.
2. The gamma setting seems to be actually changing gamma levels on my computer itself as both of my monitors get really white and washed out, though it's still clearly visible what I'm looking at.
3. Gamma now adjusts when starting a level, but it adjusts to whatever is set in Video Settings and disregards the Loader Settings for gamma, thus snapping down from 200 to the level I have adjusted in the menu upon level load.

**Comment by IceMaverick** [comment]
Issue has been partially resolved since original post:
Gamma value now adjusts to its in-game menu value when you start a mission.
In-Game Gamma always overrides Launcher Gamma values in all use-cases except the initial main menu screen.
Launcher and In-Game Gamma are still de-synched, as explained and expected.

**Comment by BinToss** [comment]
Note to self: double check if we patch the gamma setting in the player profile.

**Comment by BinToss** [comment]
This seems to be resolved. I'll re-open it if the ugly beast rears its head again.
