### ISSUE TITLE
Revise blam.sav gamepad input mappings

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#105]
While researching the Menu Accept and Menu Back actions, I'd discovered some inconsistencies with our current understanding of the file offsets.
Our current understanding is described in [Profile.cs](https://github.com/yumiris/HCE/blob/master/hxe/kernel/src/HCE/Profile.cs) as HXE.HCE.Profile.ProfileInput.Action (byte values) and HXE.HCE.Profile.ProfileInputs.Button (file offsets).

### Example 1
| Action   | Input         | Offset Range | Value
| -------- | ------------- | ------------ | -----
| Melee    | B (Button 2)  | 0x22C-0x22D  | 0xFF7F -> 0x0400
| MenuBack | B (Button 2)  | 0x32C-0x32D  | 0xFFFF -> 0x0100
#### Remarks
The offset difference is 0x1. It is also noteworthy to mention the value difference: -0x03.
#### Hypothesis
When a Button is bound to multiple actions, the second binding is written to (offset + 0x1).

### Example 2
This image compares "no bindings" to "Button 2 bound to Melee & Menu Back"
![This image compares "no bindings" to "Button 2 bound to Melee & Menu Back"](https://cdn.discordapp.com/attachments/569152356864753686/802432578728624148/Screenshot_2021-01-22_225843.png)

This is the same, but with the addition of A/Button1 bound to Jump & Menu Accept
![This is the same, but with the addition of A/Button1 bound to Jump & Menu Accept](https://cdn.discordapp.com/attachments/569152356864753686/802432744281604106/unknown.png)

| Action     | Input        | Offset Range | Value
| ---------- | ------------ | ------------ | -----
| Jump       | A (Button 1) | 0x22A-0x22B  | 0xFF7F -> 0x0000
| MenuAccept | A (Button 1) | 0x32A-0x32B  | 0xFFFF -> 0x0000
#### Remarks
The offsets in this example corresponds with the prior hypothesis, but the values are now identical.
Our previous understanding of values indicated they were the Action bound to the Input (offset).
We can only infer that the offset must be different for the two bindings, but the values can be the same for these two bindings.
If so, what happens when a different button is bound to Menu Accept?

### Example 3
| Action      | Input             | Offset Range | Value
| ----------- | ----------------- | ------------ | -----
| Menu Accept | A (Button 1)      | 0x32A        | 0x00
| Menu Accept | Start (Button 8 ) | 0x32A        | 0x07
#### Remarks
Here, we can see a correlation between the DirectInput button off and the Value.
So why is B (Button 2) so different in Example 1?

**Comment by BinToss** [comment]
The result of this endeavor will be documented on [C20](https://c20.reclaimers.net/h1/engine/files/#blam-sav).

**Comment by BinToss** [comment]
Something else interesting to note:
The default, unbound values for the offset range `0x32C` to the end of `0x33B` are all `0xFFFF` instead of `0xFF7F`.

**Comment by MirisWisdom** [comment]
1. https://docs.microsoft.com/en-us/windows/win32/api/xinput/ns-xinput-xinput_gamepad?redirectedfrom=MSDN
2. https://docs.microsoft.com/en-us/windows/win32/api/xinput/ns-xinput-xinput_keystroke

**Comment by BinToss** [comment]
This is a bit closer to what we're dealing with.
https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/directinput

**Comment by BinToss** [comment]
So, as discussed on Discord, we've surmised that the values assigned to the offsets in this special range are congruent to DirectInput button enums/bitmasks.
![image](https://cdn.discordapp.com/attachments/569152356864753686/802823139783999549/unknown.png)

**Comment by BinToss** [comment]
Resolved by #206
