### ISSUE TITLE
Fix Campaign (de)serialization

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#111]
> The resulting initc.txt does not have the campaign info because there's an exception at Kernel.cs, line 197.
![1](https://cdn.discordapp.com/attachments/569152356864753686/803422202023116834/unknown.png)

> To debug this, I broke down the line into three separate operations.
![2](https://cdn.discordapp.com/attachments/569152356864753686/803423824234283048/unknown.png)

> Doing so allowed me to determine the exception was being thrown in HXE.Campaign.Load().
> I then broke down the faulty code into multiple lines.
![3](https://cdn.discordapp.com/attachments/569152356864753686/803429085979082762/unknown.png)

Creating a new XMLSerializer with an object of type Campaign causes an exception to be thrown.

**Comment by MirisWisdom** [comment]
Resolved by #114.
