### ISSUE TITLE
Display settings are set inconsistently

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#113]
### Scenario 1
1. The user starts the loader,
2. does not access the Config menu,
3. and starts the game.
The game may start windowed in its default canvas resolution (800x600).
Is the loader not applying default config settings if none exist?

### Scenario 2
1. The user accesses the Config menu,
2. clicks _Save_,
3. and then clicks _Load SPV3_
The loader fails to load an existing player profile. In my case, my nToss profile.
The kernel then creates a new profile.
Afterwards, the game starts in exclusive fullscreen (or perhaps whatever was configured in the Config menu), but runs at the default 800x600 resolution.
Again, the native resolution isn't being applied.

**Comment by MirisWisdom** [comment]
Resolved by #114.
