### ISSUE TITLE
Loader not detected (user: Toraburu#3692)

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#156]
Campaign/Resume data not written to initc.txt
[initc.txt](https://github.com/yumiris/HCE/files/5941309/initc.txt)
![image](https://user-images.githubusercontent.com/7243190/107176173-7df87800-6983-11eb-90b1-414b12cf0f3c.png)

**Comment by BinToss** [comment]
```
 -- INIT.RESUME HALTED
 Error:  System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HXE.HCE.LastProfile.Load()
   at HXE.Kernel.<Invoke>g__Resume|7_4(<>c__DisplayClass7_0& , <>c__DisplayClass7_1& )
 -- MAIN.BLAM HALTED
 Error:  System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at HXE.HCE.LastProfile.Load()
   at HXE.HCE.Profile.Detect(String directory)
   at HXE.Kernel.<Invoke>g__Blam|7_1(<>c__DisplayClass7_0& )
```

**Comment by MirisWisdom** [comment]
Seems to be a quirk with how the last profile is inferred.

Unrelated: why screenshots of messages over copying and pasting them in plaintext?

**Comment by BinToss** [comment]
I had the screenshots saved to my desktop.

**Comment by MirisWisdom** [comment]
Best to focus on more anonymous plaintext over personally identifiable screenshots :stuck_out_tongue:

**Comment by BinToss** [comment]
I hadn't even considered that. Saving the username makes it easier for me
to co tact that person later.
Knowing me, decentralizing my workload ( saving some info in one place and
the rest of it in another place) else would lead to me becoming
disorganized and confused.

Case in point: I have some parts of the Loader's config settings mapped out
in text documents and some of it explained in a paperback notebook.

Edit: Discussing this gave me an idea. in the first post in Issues, I could put make a note to myself of the path and filename of a text document containing the usernames of people who experienced each issue. One file for each issue.

**Comment by MirisWisdom** [comment]
Ah, I wouldn't worry much about it. Quoting and refraining from 
specifying the numbers in the Discord ID could work, e.g.:

 >  i trust nobody with an anime profile pic
 >                                - Miris Wisdom

That way we get the searchability, an illusory degree of privacy, and 
also centralising your workload.

I am a nuisance.

**Comment by BinToss** [comment]
#130 rears its ugly head once again.
Fresh installs will not detect the loader.

However, now the *difficulty* is written to initc, but not the level id.

(which we already knew, but I had forgotten)
