### ISSUE TITLE
Resolve MCC (Windows Store) Verification

### ISSUE THREAD

**Issue by MirisWisdom** [HaloSPV3/HCE#197]
### Introduction

People are reporting issues with installing SPV3 when the Windows Store version of MCC is used. This issue attempts to investigate the problem and determine a solution that is:

1. Compatible with everyone's computers, including 32-bit computers;
2. Preserves the security of the verification as much as feasibly possible.

### Testing

1. [Download and extract this ZIP file](https://github.com/yumiris/HCE/files/6002599/detect.03.zip);
2. Run the Windows Store version of MCC;
3. Run the `detect.bat` file and let me know if it says that it's correctly detected the Windows Store version.

**Comment by loudCDPman** [comment]
Hi there @yumiris,
i ran it locally i think it worked. 
![image](https://user-images.githubusercontent.com/48129030/108356876-974fbe80-71e4-11eb-9c0b-690f69292754.png)
How did you fix it in the end, i was looking into 64bit exe thats signed that check the process and returns the value.

**Comment by BinToss** [comment]
Resolved by f41c6cd1 to 8a517401

Process module (halo1.dll) heuristics were removed which limits our ability to detect if the user owns CEA.
If we could find a way to restore them in the future without sacrificing x86 (32-bit) compatibility, that would be great.
For now, merging #204 on top of Miris' changes will have to suffice.

**Comment by BinToss** [comment]
I'm working on restoring the heuristics without sacrificing 32-bit compatibility.
