### ISSUE TITLE
Consistent CTD on Silent Cartographer: Evolved

### ISSUE THREAD

**Issue by IceMaverick** [HaloSPV3/HCE#2]
For no visually identifiable reason, I've encountered a consistent CTD when dying in a certain part of SC:E. 
In the video linked below, you will see that dying elsewhere in the same overall zone doesn't have any unexpected effects. However, there is a zone ranging from just before the Covenant storage boxes I stop in front of (0:35 in the video) to the archway marking the entrance to the Forerunner building ahead, dying anywhere in that stretch of land causes the game to hang and then crash to desktop with 100% consistency.

Game is being played on Legendary. 
Mission is Silent Cartographer: Evolved.
This is shortly after mission start. After clearing the landing zone and pushing down the beach past the Ghosts and Shade guarding the entrance to the videoed zone and coming here prior to visiting any other parts of the island. 

https://www.youtube.com/watch?v=EyTG4kkVabo

**Comment by BinToss** [comment]
This issue is irrelevant to the SPV3 Launcher, but thank you for reporting it.

**Comment by IceMaverick** [comment]
Is this GitHub only for the Launcher? I thought it was for the project as a whole. Where's the primary project repository in that case?

**Comment by BinToss** [comment]
Sorry, there currently isn't a public repository for the game files. The SPV3 bug tracker is currently invite-only to keep it sane.
Bug reported in the #Bug-Reporting channel in the SPV3 Discord server are added by one of the verified bug reporters to the bug tracker.

**Comment by IceMaverick** [comment]
Ah, very well. I suppose I'll report future information there then.
