### ISSUE TITLE
Restore MCC heuristics while maintaining 32-bit compatibility

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#210]
The installer mode works, but the launcher mode cannot start the game.
I'm assuming this issue lies in HXE.

**Comment by MirisWisdom** [comment]
Why restore it if things work without it?

**Comment by BinToss** [comment]
What's stopping someone from buying only Halo 3 on MCC and then running MCC
to "prove" they own CEA?

**Comment by MirisWisdom** [comment]
good taste in games

**Comment by BinToss** [comment]
![image](https://user-images.githubusercontent.com/7243190/113470636-fde31180-940b-11eb-8b78-6b551106907c.png)
It seems what I had written on March 17 works as-is.
