### ISSUE TITLE
3.3 | Warn users that more crashes may occur when EAX emulation (DSOAL) is enabled

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#33]
![image](https://user-images.githubusercontent.com/7243190/90128559-eee40d80-dd1b-11ea-9993-30b31d437721.png)
Maybe strip it out if debugging efforts confirm that Halo PC's implementation of EAX can lead to crashes.

Seeing as DSOAL hasn't led to crashes in most other custom maps, it could be a faulty sound tag or something completely unrelated that coincides with sounds before/during a crash.

**Comment by MirisWisdom** [comment]
Resolved in #90.
