### ISSUE TITLE
Gamma Dark/Light

### ISSUE THREAD

**Issue by AshySlashy92** [HaloSPV3/HCE#42]
The game is way too dark. Before I downloaded the updated version of SPV3 I was able to adjust the brightness in the game. In this new version I have the settings to max for brightness and still it is way to dark to even see anything, even in a bright environment. I would like to know if this was intentional or if it's a minor issue in the game. Or if I'm the only one having this issue. Please help me out with this issue if possible.

**Comment by BinToss** [comment]
You are using the gamma setting in the Launcher, right?

**Comment by AshySlashy92** [comment]
Yes I've tried everything.

**Comment by BinToss** [comment]
Hmmm...
http://www.lagom.nl/lcd-test/black.php
Which is the lowest numbered box you can see in this test?

btw this sounds like this issue isn't related to the launcher. This issue tracker is for SPV3's launcher, not the mod itself.

**Comment by BinToss** [comment]
Are you still having this problem?

**Comment by BinToss** [comment]
Hello?

**Comment by MirisWisdom** [comment]
See if #1 resolves anything - feel free to re-open if problems persist.
