### ISSUE TITLE
Disable cinematic "fake widescreen" bars by default

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#47]
Part of #44 

These are stupid unless the video source is 4:3. Their intended use is to crop a scene from 4:3 to 16:9 or wider.
We don't need that in this age dominated by wide, extra-wide, and ultra-wide displays.
I don't think it's necessary even in 4:3.

Spiel done.

https://github.com/yumiris/SPV3/blob/376079c1e254c2169f61189342152e34992cccf0/src/Configuration.Loader.cs#L41

https://github.com/yumiris/HXE/blob/f00389e018aac9db4250843f9f29c2d5e9f042e4/src/Kernel.cs#L1034

**Comment by MirisWisdom** [comment]
Resolved in 802401558db0d9956e1d8372ddb492dfd2b521fa.

**Comment by MirisWisdom** [comment]
Got scammed, the aforementioned commit doesn't change the default value grr

**Comment by BinToss** [comment]
It doesn't? God f...

**Comment by MirisWisdom** [comment]
Resolved in f7f8aa0aaf7843ca63ed0c4e93ca3165ada8f514.

**Comment by MirisWisdom** [comment]
Got scammed again, `_cinematic` got renamed to `_cinemabars` without updating the references elsewhere.

https://github.com/yumiris/SPV3/blob/f7f8aa0aaf7843ca63ed0c4e93ca3165ada8f514/src/Configuration.Loader.cs#L41
The following needs to reference `_cinemabars`:
https://github.com/yumiris/SPV3/blob/f7f8aa0aaf7843ca63ed0c4e93ca3165ada8f514/src/Configuration.Loader.cs#L216-L225

**Comment by BinToss** [comment]
Ah, THAT'S what I forgot to do!  Good catch.

**Comment by BinToss** [comment]
hold up...
https://github.com/VoidsShadow/SPV3/commit/145bc3e3fbfd0a7407dacebfe6fdb3ff16bcd97e
I had already fixed it. Maybe I forgot to let you know I force-pushed.

**Comment by MirisWisdom** [comment]
Resolved in 3cc3793936a20575a322ade7018bdc6694393392.
