### ISSUE TITLE
Add draggable Window Top-Bar

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#52]
How do we override Windows' theme for this application? Other software can do it. 
A Modern/Material theme would be preferred.

**Comment by MirisWisdom** [comment]
Resolved in 4624bf3bacc4a1dc7d7c09d262e36e42c671883a:

![image](https://user-images.githubusercontent.com/10241434/97867577-12ca5480-1d49-11eb-84c8-39eba8ed4f64.png)
