### ISSUE TITLE
add checkbox for native resolution

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#7]
Additionally, disable the custom resolution boxes. Replace text with native resolution. Revert the text to the last custom resolution when the native resolution option is unchecked.

This issue was brought to light by Discord user Rocky.S Rogers#4655, who was having trouble figuring out which resolution to use.

**Comment by MirisWisdom** [comment]
Good idea, will get around to it very soon.

**Comment by MirisWisdom** [comment]
Implemented in [this build](https://file.n2.network/f/628ae5ff5bcd446a89a8/?dl=1), which was compiled from [this commit](https://github.com/yumiris/SPV3/commit/3b72ff06919f027c9f48a6d37dba25fa8a5e7c08). Let me know if it's causing any issues.

**Comment by BinToss** [comment]
Regarding 0318's "native res' checkbox, the checkbox would be more noticeable if it is closer to the resolution input fields.

**Comment by MirisWisdom** [comment]
Fixed in [this commit](https://github.com/yumiris/SPV3/commit/eaf2d3f4dfdc7b213e45007aca5060f73edee23d):
![image](https://user-images.githubusercontent.com/10241434/75701408-b52fc500-5cee-11ea-99f9-db6ee5db07f2.png)
