### ISSUE TITLE
LUA can now read and write files

### ISSUE THREAD

**Issue by SubhadeepJasu** [HaloSPV3/HCE#75]
Kirby developed a custom chimera utility which removes most of the restrictions. According to him it is possible to read and write files with it. So, hopofully the post processing system will be using normal files stored else where instead of initc. We can also do that for all of them. @yumiris What do you say?

**Comment by BinToss** [comment]
It's about time!

**Comment by BinToss** [comment]
Oh, it was transferred! I should have read into it more.
