### ISSUE TITLE
Enable NTFS compression during Install/deployment

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#82]
### Summary
If it's applied to a new directory, every new item under it will inherit the compression attribute.
If it's applied to files, it needs to be re-applied when files are replaced.

We could make it an option during installation.
A checkbox with a warning that notifies the user NTFS compression will save space at the cost of slightly longer hitches during Loading sections of gameplay. These hitches are particularly unpleasant with Open Sauce due to its Velocity buffer also hitching when the frame rate drops below the tick rate. Luckily, these Loading zones are rarely placed where the player would be in combat.

### Data Savings
![](https://cdn.discordapp.com/attachments/682885060256727047/775246198893576222/unknown.png)

### Programmatically applying the Compression attribute
* https://docs.microsoft.com/en-us/windows/win32/fileio/compression-attribute
  > To modify the FILE_ATTRIBUTE_COMPRESSED attribute for a file or directory, you must use the DeviceIoControl function with the FSCTL_SET_COMPRESSION control code.
* https://stackoverflow.com/questions/624125/compress-a-folder-using-ntfs-compression-in-net
  > Several methods of executing the win32 functions from C#/DotNet.

**Comment by BinToss** [comment]
Partially implemented in my fork.
Currently, it only enables it on a folder which will only affect *new* items in the folder.
To make it retroactively apply to existing items, I would need to apply it recursively to all subdirectories and items.

**Comment by BinToss** [comment]
# Operating System and File System Support

## NTFS
### Windows
Partially implemented, but needs to recursively apply the attribute.
NTFS only supports LZNT1 compression and is the default method

1. We can scan through a directory and determine which items are not compressed using the following methods
  1.[FSCTL_GET_COMPRESSION IOCTL](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_get_compression)
  2.[GetFileAttributesA](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfileattributesa) 
2. Then we apply compression using...
  1.[FSCTL_SET_COMPRESSION IOCTL (winioctl.h)](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_set_compression)

#### GetDriveFormat
We need to know if the selected drive/volume supports compression.

We can read the [System.IO.DriveInfo.DriveFormat](https://docs.microsoft.com/en-us/dotnet/api/system.io.driveinfo.driveformat?view=net-5.0#System_IO_DriveInfo_DriveFormat) property to learn the file system format. 
* Which formats are supported?
* Code Examples
  * [How do I retrieve disk information in C#?](https://stackoverflow.com/questions/412632/how-do-i-retrieve-disk-information-in-c)

### Linux
The Linux kernel has had native support for NTFS since version 2.6.14.
* Code Examples
  * [How do I see and set the NTFS compression attribute in Linux?](https://superuser.com/questions/1358286/how-do-i-see-and-set-the-ntfs-compression-attribute-in-linux)



## ZFS
### Windows
Unofficially supported by an [incomplete, third-party driver](https://github.com/openzfsonwindows/ZFSin/).
Whether or not we should support this is to be determined...later.

### Linux via [OpenZFS](https://github.com/openzfs/zfs/) kernel module
Although integrated into Ubuntu by default via OpenZFS, ZFS is not natively supported by the Linux kernel due to code licensing conflicts. This may change when the OpenZFS 2.0.0 release (Nov20, 2020) is reviewed.
OpenZFS 2.0.0 supports OpenBSD and Linux.

## Ext2/Ext3
Ext1/2/3/4 file systems do not have native file compression support, but 2/3 have third-party extensions which provide the feature.

### Windows
Native ext file system support on Windows was non-existent [until Windows 10 Preview Build 20211](https://www.bleepingcomputer.com/news/microsoft/windows-10-now-lets-you-mount-linux-ext4-filesystems-in-wsl-2/).
Third-party driver/kernel support is sparse and poor.
Because of this and because Ext requires an extension to add file compression, we can't support Ext compression extensions for Windows without making it ourselves.

### Linux via Ext2Compr/Ext3Compr

**Comment by MirisWisdom** [comment]
Resolved in #90.
