### ISSUE TITLE
On new builds, delete old loader0x01.bin and kernel0x01.bin files.

### ISSUE THREAD

**Issue by BinToss** [HaloSPV3/HCE#87]
Attempting to load old, incompatible files with different offsets may cause memory corruption or lead to other unexpected issues.

**Comment by BinToss** [comment]
Should we write the loader/kernel version to the files?

**Comment by MirisWisdom** [comment]
Important priorities: assigning the loader version into the binary's header for compatibility inference;
Miris priorities: `~yumiris` in the binary's header.

Safe to proceed with deleting it all, though speaking of settings files, I do wonder if we should migrate away from the custom binary files, to XML or even an SQLite database...

**Comment by BinToss** [comment]
Adding the version byte to the files was a mistake that can't be reversed at this point.
I'm satisfied with changing the binary file's filename until we ditch the binary save system.

**Comment by BinToss** [comment]
Closed by

**Comment by BinToss** [comment]
Resolved by https://github.com/yumiris/HCE/commit/87dac48b2a3e77f461268fedf14fafa68239e703
