### ISSUE TITLE
Resolve configuration for custom resolution, FOV, DSOAL

### ISSUE THREAD

**Issue by SubhadeepJasu** [HaloSPV3/HCE#99]
![image](https://user-images.githubusercontent.com/20795161/104844487-81559200-58f6-11eb-99d4-fbc1fca9291c.png)
![image](https://user-images.githubusercontent.com/20795161/104844561-ef01be00-58f6-11eb-9279-9d3d4d410726.png)

**Comment by BinToss** [comment]
- [x] Resolution can be changed (double-check native resolution code)
- [x] FOV can be changed
- [x] DSOAL can be enabled
- [x] SSR performance warning only shown when the user toggles the setting.
- [x] Persistent settings

**Comment by BinToss** [comment]
I may have found the cause of the FOV issue
![image](https://user-images.githubusercontent.com/7243190/104872393-a3551180-5902-11eb-994d-b76505c78450.png)
That's checking the non-SPV3 file path.

**Comment by BinToss** [comment]
![image](https://user-images.githubusercontent.com/7243190/104874202-33955580-5907-11eb-9f69-d946bc0a9009.png)
This appears to be helpful when an invalid resolution is set, but less so if someone runs their game at a higher resolution than their desktop. I used to do that when I still used a Radeon HD 7870 GPU. Desktop was 1920x1080, but I ran games at 2560x1440 via VSR.
I don't think we've run into this issue yet so I'll leave it be.

**Comment by BinToss** [comment]
The erased Loader settings may have been caused by assignments happening in the wrong order. I've changed the call order for SPV3.Configuration.Save() and Load().

**Comment by BinToss** [comment]
The patch still needs to be tested, so it's not ready to be merged.

**Comment by BinToss** [comment]
With the merging of #108, the checklist will be completed and this Issue is resolved.

**Comment by BinToss** [comment]
The Display Settings are still inconsistent
See #113

**Comment by MirisWisdom** [comment]
Resolved by #114.
